version: 0.2
env:
  parameter-store:
    NOTION_DATABASE_ID: "/portfolio/NOTION_DATABASE_ID"
    NOTION_TOKEN: "/portfolio/NOTION_TOKEN"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./out s3://oisenhart-portfolio --delete
      - aws cloudfront create-invalidation --distribution-id E28PC9PF1TACFJ --paths "/*"