// yellowtail for "After Dark"
// Pirata One for Logo in dark mode
// Piazzolla for body text
// IBM Plex Sans for bigger text
import { Providers } from './providers' // <-- Import your new providers file
import type { Metadata } from "next";
import { Pirata_One, Yellowtail, Piazzolla, IBM_Plex_Sans, IBM_Plex_Mono, Ubuntu, Titillium_Web, Lekton, Space_Grotesk} from "next/font/google";
import "./globals.css";

const pirata = Pirata_One({
  variable: "--font-pirata",
  subsets: ["latin"],
  weight: "400",
});

const yellowtail = Yellowtail({
  variable: "--font-yellowtail",
  subsets: ["latin"],
  weight: "400",
});


const mono = IBM_Plex_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: "400",
});

const sans = IBM_Plex_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: "400",
});

const space = Space_Grotesk({
  variable: "--font-space",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${pirata.variable} ${yellowtail.variable} ${space.variable} ${sans.variable} ${mono.variable} antialiased relative flex min-h-svh flex-col overflow-x-hidden`}
      >
        <Providers>
          {children}
        </Providers>
        
      </body>
    </html>
  );
}
