export const projects = [
  {
    id: 1,
    title: "HackLab",
    coverImage: "/images/projects/hacklabCover.avif",
    description: "A web app for developers to find teams and enhance the development process for projects.",
    overview: "HackLab was the 1st place and best design winner at the ACM Projects Spring 2025 presentation night. I worked on the backend of the project where I built a Node and Express API deployed on AWS EC2, real-time chat using socket.IO, an AI resume generator using Gemini, the GitHub API, and LinkedIn web scraping to create tailored LaTeX resumes for the user. Me and the other guy on the backend also made a swagger spec detailing the API routes for easier integrations. The project is full of other features not listed here so if you're interested I highly encourage you to check out the repository for yourself.",
    skills: ["Node.js", "AWS", "PostgreSQL", "Websockets", "Next.js", "Tailwind"],
    features: [
      "AI Project Generation:Our AI assistant Juno suggests tech stacks, MVPs, timelines, and even project thumbnails based on your skills and goals.",
      "Auto Resume Builder:Instantly generates a polished, customizable resume using your LinkedIn and GitHub data, PDF and LaTeX included.",
      "GitHub Integration:Users login via GitHub OAuth, creates project repos automatically, and reads commit history for resume insights.",
      "Real-Time Chat:Each project has a dedicated chat, plus private messaging for one-on-one communication."
    ],
    link: "https://github.com/acm-projects/HackLab",
    ongoing: false,
  },
  {
    id: 11,
    title: "Enarc Exchange",
    coverImage: "/images/projects/comingsoon.avif",
    description: "A UTD-themed prediction market where students bet 'Temoc Tokens' on campus events.",
    overview: "Enarc Exchange is a prediction market platform designed specifically for the UTD community, allowing students to bet on academics, sports, and campus life using a virtual currency called 'Temoc Tokens'. As the project manager, I led a team of 5 over 6 weeks to build and deploy the project. My responsibilities included overseeing the development process, coordinating between frontend and backend teams, and ensuring timely delivery of features. However, I did also do a lot of development given the tight schedule.",
    skills: ["Node.js", "PostgreSQL", "Socket.io", "AWS", "JWT", "Docker"],
    features: [
      "Predictive Markets: Bet on UTD-specific events using the LMSR pricing model for dynamic odds.",
      "UTD Exclusive Authentication: Secure sign-up restricted to @utdallas.edu emails with JWT-based sessions and a 500 token starting balance.",
      "Real-time Data: Live market updates and chat feeds powered by Socket.io to keep users engaged.",
      "User Profiles: Full CRUD functionality to track profits, losses, active bets, and transaction history."
    ],
    link: "https://github.com/Owen-Isenhart/EnarcExchange",
    ongoing: false,
  },
  {
    id: 2,
    title: "BPSmith",
    coverImage: "/images/projects/bpsmithCover.avif",
    description: "A web app for applying or creating .bps patch files for Super Mario 64 ROMs.",
    overview: "ROM Hacks work by creating a bps file by comparing the changes made between an original ROM with a modified ROM, and saving the differences. Then, the bps file can be applied to an original ROM to create the modified ROM from which it came from. This is done to allow the legal distribution of ROM hacks. There are other file formats that can do this as well (ips, ups, etc.), but bps is often better due to supporting larger files, ensuring patch integrity with built-in checksums, and creating smaller patches through delta encoding. So, with BPSmith, you can become a bps blacksmith, and easily apply or create patches in an instant! BPSmith is designed with a focus on a clean, intuitive user interface and a smooth user experience, making the patching process straightforward for everyone, from beginners to experienced ROM hackers.",
    skills: ["Bit Manipulation", "File Processing", "Encoding", "Next.js", "UI/UX"],
    features: [
        "Apply Patches:Easily apply .bps patches to your ROMs.",
        "Create Patches:Create your own .bps patches from modified ROMs."
    ],
    link: "https://github.com/Owen-Isenhart/BPSmith",
    ongoing: false,
  },
  {
    id: 3,
    title: "Planet Destroyer",
    coverImage: "/images/projects/planetdestroyerCover.avif",
    description: "An incremental game built in C# XNA; Generated 180+ itch.io downloads.",
    overview: "Planet Destroyer is an addictive incremental (cookie clicker-style) game where you buy ships and upgrade your abilities to destroy planets. It was developed in C# using the XNA framework and gained popularity on itch.io. This was a fun project to make because the XNA framework is incredibly minimalist, meaning you have to make essentially everything yourself from basic rectangles and tracking user input. I also made most of the games' texture assets myself and really enjoyed creating the pixel art spritesheets. The game scales nicely and is a very interactive experience with fully customizeable settings (including audio, video, and performance). Check out the repository if you're interested! (Disclaimer: it is windows exclusive and will only run on certain windows machines)",
    skills: ["C#", "XNA", "Animation", "Game Design", "Pixel Art"],
    features: [
        "Incremental Gameplay:Buy ships from the store, upgrade certain stats, unlock achievements, and eventually prestige as you progress through the game.",
        "Customizeable Settings:Adjust audio (music, sound effects, etc) and video (resolution, performance mode) settings at the click of a button to customize your experience. Additionally, the game automatically saves and remembers your progress and settings so they'll be set for future sessions.",
        "Pixel Art Graphics:Enjoy the retro-inspired visuals made by yours truly.",
    ],
    link: "https://github.com/Owen-Isenhart/PlanetDestroyer",
    ongoing: false,
  },
  {
    id: 4,
    title: "rawr",
    coverImage: "/images/projects/comingsoon.avif",
    description: "(root access: wipe royale) A platform for agents hacking agents",
    overview: "rawr is a website where you can train your own agent like a pokemon and upgrade it with different skills, and then have it battle other agents all running in docker containers where the objective is to hack the other agents offline, and the last agent standing wins.",
    skills: ["Python", "Docker", "AI", "Web Development"],
    features: [
        "Agent Training:Train your agent with different skills and strategies to prepare it for battle.",
        "Real-Time Battles:Watch your agent battle against others in real-time, with the goal of hacking the opponent offline.",
        "Community Engagement:Join a community of like-minded individuals who are passionate about AI and cybersecurity."
    ],
    link: "https://github.com/Owen-Isenhart/rawr",
    ongoing: true,
  },
  {
    id: 6,
    title: "Portfolio",
    coverImage: "/images/projects/portfolioCover.avif", 
    description: "The website you're on right now!",
    overview: "This site hosts imformation about me, my projects, and my occasional notes. I made it in Next.js with Tailwind, my notes integrate from Notion's API, and is deployed using AWS Amplify and Route 53.",
    skills: ["Next.js", "Tailwind", "Notion API", "AWS"],
    features: [ 
      "All Green Google Lighthouse Report:Optimized the site and achievied 94+ in every metric (Performance, Accessibility, Best Practices, and SEO)",
      "UI and Responsiveness:I carefully crafted the feel and look of this website to make it a smooth experience, and made sure no matter the screen size everything displays properly",
    ],
    link: "https://github.com/Owen-Isenhart/Portfolio",
    ongoing: false,
  },
  {
    id: 7,
    title: "Pentagon Pizza",
    coverImage: "/images/projects/penpizzaCover.avif", 
    description: "A web app for tracking how busy pizza resturants near the Pentagon are.",
    overview: "Pentagon Pizza is based on a real-world theory: a spike in late-night pizza orders at the Pentagon often precedes a major global crisis. This application automates the monitoring process, providing an early warning system for significant geopolitical events. By scraping data from pizza establishments in close proximity to the Pentagon, our system analyzes activity levels in real-time. When these levels cross a pre-defined threshold, a 'High Threat Level' is triggered, and an alert is immediately sent out.",
    skills: ["Next.js", "Tailwind", "Webscraping", "Discord.js", "Webhooks"],
    features: [
      "Real-time Web Scraping:Utilizes Scrapingdog's Google SERP API to grab the html of resturant's google business profile which is then parsed through to determine how busy they are.",
      "Threat Level Analysis:Compiles how busy the nearest pizza places are and determines the threat level using a weighted algorithm.",
      "Email Notifications:Users can enter their email to get notified of high threat levels. Their email is sent to formspree which triggers a webhook connected to a discord server, and then a discord bot can then email all users alerts.",
    ],
    link: "https://github.com/Owen-Isenhart/Pentagon-Pizza",
    ongoing: false,
  },
  {
    id: 8,
    title: "SpeedFools",
    coverImage: "/images/projects/speedfoolsCover.avif", 
    description: "A website hosting tutorials for SM64 speedruns.",
    overview: "Super Mario 64 speedrunning is an incredibly niche thing to do. However, it's a suprisingly popular thing to watch. On YouTube and Twitch, SM64 speedruns get many views and have a massive following. So I put two and two together, and realized that people really like the game, but there's just such a high barrier to entry that pushes a lot of new people away. As a (now washed, but at one point good) speedrunner of the game myself, I took it upon myself to record and edit hundreds of videos detailing exactly how to do certain tricks and mechanics, and then wrote an extensive guide on resources for how to source equipment and further information.",
    skills: ["HTML", "CSS", "JS"],
    features: [
      "Accomodates All Levels:I recorded videos showing multiple strategies for each star of each category, so anyone from someone who's never played the game to someone contending for a world record has something they can take away.",
    ],
    link: "https://github.com/Owen-Isenhart/SpeedFools",
    ongoing: false,
  },
  {
    id: 9,
    title: "FHS CS Club Website",
    coverImage: "/images/projects/fhsCover.avif", 
    description: "The website for the cs club at FHS.",
    overview: "I was an officer for my highschool's computer science club and at that point the club struggled with advertising and coordination, so I built this website to centralize the club's information, allow marketing officers to link it to a QR code for better advertising, and help new members with valuable cs resources. This was the first website I ever deployed! :)",
    skills: ["HTML", "CSS", "JS"],
    features: [
      "Officers Page:Find who the current officers are so you know who to talk to if you have a question.",
      "Events Page:Keep up to date with the club's plans for upcoming events.",
      "Resources Page:Learn about computer science, languages, and reccomendations for IDEs.",
    ],
    link: "https://github.com/Owen-Isenhart/cs-website",
    ongoing: false,
  },
  {
    id: 10,
    title: "RoomRunner",
    coverImage: "/images/projects/roomrunnerCover.avif",
    description: "A side scrolling Jetpack Joyride style game.",
    overview: "Made in a team of 3 others for a videogame programming class in C# using the XNA framework. Game includes many features like boss fights, powerups, cosmetics, random obstacles and hazards, infinite levels, quests, customizeable settings and music, and more. My main contributions included the development of the shop, powerups, quests, tutorial, game art, settings and menus, and managing git merges.",
    skills: ["C#", "XNA", "Agile Development", "Pixel Art", "File I/O"],
    features: [
      "Infinite Levels:The game goes as long as you do. The level designs connect seamlessly together allowing you to go until you die. In each level, there's eventually a boss battle that you have to beat in order to move on to the next level.",
      "Shop:Each run you collect coins, and with those coins you can buy powerups for the next run like time control, invincibility, instakill, or a coin magnet. You can also deck out your character with some sick hats I made in the costmetics shop.",
    ],
    link: "https://github.com/Christian-Zech/RoomRunner",
    ongoing: false,
  },
  
  // {
  //   id: 12,
  //   title: "oatsDB",
  //   coverImage: "/images/projects/comingsoon.avif",
  //   description: "A high-security database engine featuring automated data decay and cryptographic audit trails.",
  //   overview: "OatsDB (Observable Audit & Temporal Shredding) is a database project focused on privacy and verifiable security. I am building the engine in C++ with a focus on 'Observable Audit & Temporal Shredding' (O.A.T.S.), implementing cryptographic Time-To-Live (TTL) for secure data decay and a Merkle Tree ledger to provide a verifiable audit trail for all operations. The system utilizes an LSM-Tree (Log-Structured Merge-Tree) architecture for high-performance writes and leverages libsodium for robust cryptographic primitives.",
  //   skills: ["C++", "LSM-Trees", "Cryptography", "Systems Programming", "libsodium"],
  //   features: [
  //     "Cryptographic Data Decay: Automatic and secure shredding of data based on predefined expiration settings.",
  //     "Verifiable Audit Trail: A Merkle Tree-backed ledger that allows users to verify the integrity and history of the database.",
  //     "High-Performance Storage: Optimized for write-heavy workloads using a custom log-structured merge-tree implementation."
  //   ],
  //   link: "https://github.com/Owen-Isenhart/OatsDB",
  //   ongoing: true,
  // },
  {
    id: 13,
    title: "Furrow",
    coverImage: "/images/projects/comingsoon.avif",
    description: "A B2B labor routing and optimization engine designed for large-scale agricultural operations.",
    overview: "Furrow is a logistics engine designed to tackle labor, the largest expense in the agricultural industry. The platform provides sophisticated labor routing and task optimization to streamline farm workflows.",
    skills: ["C++", "Eigen", "OpenCV", "Optimization", "Logistics"],
    features: [
      "Labor Routing Engine: Advanced algorithms to optimize worker movement and resource allocation across large fields.",
      "Real-time Adaptivity: Dynamic routing that adjusts to external factors like equipment status and shifting weather patterns.",
      "Logistics Optimization: A B2B solution focused on reducing overhead and increasing efficiency in agricultural production."
    ],
    link: "https://github.com/Owen-Isenhart/Furrow",
    ongoing: true,
  },
];
